### ISSUE TITLE
How to make the file, mentioned instructions are unclear?

### ISSUE THREAD

**Issue by CalmWaves** [miyosuda/TensorFlowAndroidDemo#1]
#I am beginner, 
I have installed NDK with Android studio, but I have trouble setting path to NDK and running the make file

**Comment by miyosuda** [comment]
Sorry for unclear document.

This project is not using NDK feature in AndroidStudio, so NDK command should be called outside Android Studio Project.

Please set path for NDK by adding lines in ".profile" file in your home directory. For example,

    export NDK_HOME="/home/miyoshi/development/android/android-ndk-r11c"
    export PATH=$PATH:$NDK_HOME

and then

    source ~/.profile

and
 
    $ cd jni-build
    $ make
    $ make install

If you type "make", then make command will read "Makefile", and execute command written in Makefile.
 
This Makefile is a short text file.

https://github.com/miyosuda/TensorFlowAndroidDemo/blob/master/jni-build/Makefile

    build:
    	ndk-build
    
    install:
    	cp -r libs/armeabi-v7a/*.so ../app/src/main/jniLibs/armeabi-v7a/

    clean:
    	rm -r obj
    	rm -r libs

if you type

    $ make

then default "build:" task is executed with calling 

    $ ndk-build

and if you type

    $ make install

then 

    $ cp -r libs/armeabi-v7a/*.so ../app/src/main/jniLibs/armeabi-v7a/

is called.

**Comment by CalmWaves** [comment]
Thank your for the explanation and it worked well, 

but now I want to I want to build the project  for **intel x86** emulator instead of armeabi v7. Since app crashes with intel x86 CPU emulator. I am using Ubuntu 14.04,
          Android Studio 2.0
          NDK 10re
