### ISSUE TITLE
E/CameraService: Permission Denial: can't use the camera

### ISSUE THREAD

**Issue by ThomasPalomares** [miyosuda/TensorFlowAndroidDemo#3]
Hi, 
 
while running the repo in Android Studio after building the jni code, the app stops prematurely with the message on the phone "Unfortunately, Tensorflow Demo has stopped"

On logcat, the last log displayed with the error is:
06-20 12:58:45.997 2913-2913/org.tensorflow.tensorflowdemo I/tensorflow: CameraConnectionFragment: Chosen size: 640x360
06-20 12:58:46.014 490-32169/? W/ServiceManager: Permission failure: android.permission.CAMERA from uid=10165 pid=2913
06-20 12:58:46.015 490-32169/? E/CameraService: Permission Denial: can't use the camera pid=2913, uid=10165
06-20 12:58:46.049 2913-2913/org.tensorflow.tensorflowdemo D/AndroidRuntime: Shutting down VM

Did someone else have the same issue ? How to add permission access to the app from the phone ?

By manually adding permissions to camera and storage from the phone, the app runs correctly.

Thanks

**Comment by ThomasPalomares** [comment]
It was actually fixed in this commit from the original tensorflow repo: https://github.com/tensorflow/tensorflow/commit/b184d46e23064b33f5aa351c476b97b2d2167021

And thanks for making a version runnable in Gradle !

**Comment by miyosuda** [comment]
@ThomasPalomares 
Ah, thanks. I'll apply this change to my repo later.
